export const IntentType = Object.freeze({
  ATTACK: "ATTACK",
  DODGE: "DODGE",
  PASS: "PASS",
});

export const IntentError = Object.freeze({
  COMBAT_NOT_ACTIVE: "COMBAT_NOT_ACTIVE",
  INVALID_ACTOR: "INVALID_ACTOR",
  NOT_ACTOR_TURN: "NOT_ACTOR_TURN",
  ACTOR_DEFEATED: "ACTOR_DEFEATED",
  INVALID_TARGET: "INVALID_TARGET",
  TARGET_DEFEATED: "TARGET_DEFEATED",
  FRIENDLY_TARGET: "FRIENDLY_TARGET",
  ACTION_NOT_AVAILABLE: "ACTION_NOT_AVAILABLE",
});
