import { StyleSheet } from "react-native";
import { colors } from "./colors.js";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { padding: 18, paddingBottom: 36 },
  safe: { flex: 1, backgroundColor: colors.background },
  eyebrow: { color: colors.cyan, fontSize: 11, letterSpacing: 2, textTransform: "uppercase" },
  title: { color: colors.text, fontSize: 30, fontWeight: "400", marginTop: 10, marginBottom: 8 },
  subtitle: { color: colors.muted, fontSize: 14, lineHeight: 21, marginBottom: 20 },
  sectionTitle: { color: colors.text, fontSize: 19, fontWeight: "400", marginTop: 24, marginBottom: 10 },
  label: { color: colors.muted, fontSize: 11, letterSpacing: 1, textTransform: "uppercase", marginBottom: 7 },
  input: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceRaised, color: colors.text, padding: 13, fontSize: 15, borderRadius: 3 },
  button: { borderWidth: 1, borderColor: colors.orange, padding: 14, alignItems: "center", borderRadius: 3, marginTop: 14 },
  buttonText: { color: colors.orange, fontSize: 12, letterSpacing: 1, textTransform: "uppercase" },
  buttonDisabled: { opacity: 0.4 },
  error: { color: colors.red, borderLeftWidth: 2, borderLeftColor: colors.red, paddingLeft: 10, marginTop: 14, lineHeight: 20 },
  status: { color: colors.muted, marginTop: 12, lineHeight: 20 },
  card: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 14, borderRadius: 3, marginBottom: 9 },
  cardSelected: { borderColor: colors.cyan, backgroundColor: "#0b171b" },
  cardHostile: { borderColor: colors.red },
  cardTitle: { color: colors.text, fontSize: 16, marginBottom: 5 },
  cardBody: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  cardMeta: { color: colors.cyan, fontSize: 11, marginTop: 8 },
  combatTopBar: { minHeight: 50, flexDirection: "row", alignItems: "center", paddingHorizontal: 10, borderBottomWidth: 1, borderColor: colors.border, backgroundColor: colors.background },
  iconButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
  menuIcon: { color: colors.cyan, fontSize: 22 },
  combatTopTitle: { color: colors.text, fontSize: 18, marginLeft: 4, flex: 1 },
  chatList: { flex: 1 },
  chatContent: { paddingHorizontal: 14, paddingTop: 12, paddingBottom: 12 },
  message: { maxWidth: "88%", padding: 10, marginBottom: 7, backgroundColor: colors.surface, borderLeftWidth: 2 },
  messageLeft: { alignSelf: "flex-start", borderLeftColor: colors.border },
  messageRight: { alignSelf: "flex-end", borderLeftColor: colors.cyan },
  messageDice: { borderLeftColor: colors.violet },
  messageSender: { color: colors.muted, fontSize: 10, textTransform: "uppercase", marginBottom: 4 },
  messageText: { color: colors.text, lineHeight: 20 },
  composerArea: { paddingHorizontal: 10, paddingTop: 7, borderTopWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  commandInput: { minHeight: 44, maxHeight: 50, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceRaised, color: colors.text, paddingHorizontal: 12, paddingVertical: 9, fontSize: 15, borderRadius: 3 },
  keyboardHint: { color: colors.muted, fontSize: 11, marginTop: 5, textAlign: "right" },
  interpretationBox: { borderLeftWidth: 2, borderLeftColor: colors.cyan, paddingLeft: 9, marginBottom: 7 },
  interpretationDetail: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 2 },
  suggestionChip: { borderWidth: 1, borderColor: colors.cyan, padding: 8, marginTop: 6, borderRadius: 3 },
  suggestionText: { color: colors.cyan, fontSize: 13 },
  suggestionDetail: { color: colors.muted, fontSize: 11, marginTop: 2 },
  skipButton: { borderWidth: 1, borderColor: colors.orange, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 3 },
  skipText: { color: colors.orange, fontSize: 11, textTransform: "uppercase" },
  semanticDefault: { color: colors.text },
  semanticCharacter: { color: colors.cyan, fontWeight: "600" },
  semanticCreature: { color: colors.red, fontWeight: "600" },
  semanticItem: { color: "#f5c56b", fontWeight: "600" },
  semanticSpell: { color: "#b6a0ff", fontWeight: "600" },
  semanticAction: { color: colors.orange, fontWeight: "600" },
  semanticDamage: { color: "#ff704d", fontWeight: "600" },
  semanticDice: { color: colors.violet, fontWeight: "600" },
  overviewBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,.68)", paddingHorizontal: 14 },
  overviewPanel: { maxHeight: "88%", backgroundColor: colors.surfaceRaised, borderWidth: 1, borderColor: colors.cyan, borderRadius: 4 },
  overviewHeader: { minHeight: 50, flexDirection: "row", alignItems: "center", paddingLeft: 14, borderBottomWidth: 1, borderColor: colors.border },
  overviewTitle: { flex: 1, color: colors.text, fontSize: 17 },
  closeButton: { width: 46, height: 46, alignItems: "center", justifyContent: "center" },
  closeText: { color: colors.cyan, fontSize: 28, fontWeight: "300" },
  overviewContent: { padding: 14, paddingBottom: 24 },
  overviewMeta: { color: colors.muted, fontSize: 11, lineHeight: 18, marginBottom: 8 },
  overviewSectionTitle: { color: colors.cyan, fontSize: 11, letterSpacing: 1, textTransform: "uppercase", marginTop: 13, marginBottom: 7 },
  overviewParticipant: { flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderColor: colors.border, paddingVertical: 9 },
  overviewName: { color: colors.text, fontSize: 15 },
  overviewBody: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  inspectorPanel: { maxHeight: "82%", backgroundColor: colors.surfaceRaised, borderWidth: 1, borderColor: colors.cyan, borderRadius: 4 },
  semanticInspectorKind: { color: colors.orange, fontSize: 11, letterSpacing: 1, marginBottom: 8 },
  inspectorRow: { borderBottomWidth: 1, borderColor: colors.border, paddingVertical: 9 },
  inspectorLabel: { color: colors.cyan, fontSize: 11, textTransform: "uppercase", marginBottom: 3 },
  presentationSettings: { borderTopWidth: 1, borderColor: colors.border, marginTop: 18, paddingTop: 4 },
  settingRow: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  volumeRow: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  volumeControls: { flexDirection: "row", gap: 8 },
  volumeButton: { color: colors.cyan, borderWidth: 1, borderColor: colors.border, minWidth: 36, paddingVertical: 6, textAlign: "center", fontSize: 18 },
  progress: { marginBottom: 6 },
  progressLabel: { color: colors.text, fontSize: 13, marginTop: 8 },
  progressTrack: { height: 3, backgroundColor: colors.border, marginTop: 8, marginBottom: 4 },
  progressFill: { height: 3, backgroundColor: colors.cyan },
  choiceRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 8 },
  smallChoice: { borderWidth: 1, borderColor: colors.border, paddingVertical: 6, paddingHorizontal: 9, borderRadius: 3 },
  smallChoiceSelected: { borderColor: colors.cyan, backgroundColor: "#0b171b" },
  smallChoiceText: { color: colors.text, fontSize: 11 },
  removeText: { color: colors.red, fontSize: 11, marginTop: 10 },
  editText: { color: colors.cyan, fontSize: 12 },
  serverOption: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 14, borderRadius: 3, marginBottom: 9 },
  serverOptionSelected: { borderColor: colors.cyan, backgroundColor: "#0b171b" },
  connected: { color: colors.green, marginTop: 14, lineHeight: 20 },
  version: { color: colors.muted, fontSize: 11, textAlign: "center", marginTop: 24 },
  diagnostic: { borderLeftWidth: 2, borderLeftColor: colors.red, paddingLeft: 10, marginTop: 16 },
  diagnosticTitle: { color: colors.red, fontSize: 16, marginBottom: 5 },
  diagnosticMeta: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 7 },
  diagnosticActions: { flexDirection: "row", gap: 8 },
  detailsToggle: { color: colors.cyan, fontSize: 11, marginTop: 10 },
});
