import { StyleSheet } from "react-native";
import { colors } from "./colors.js";
import { typography } from "./typography.js";
import { borders, radii, spacing } from "./metrics.js";

const display = { fontFamily: typography.displayFamily };
const body = { fontFamily: typography.bodyFamily };

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background },
  content: { paddingHorizontal: spacing.lg, paddingTop: spacing.xl, paddingBottom: spacing.xxxl },
  loadingScreen: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.background },
  loadingMark: { color: colors.cyan, ...display, ...typography.section, letterSpacing: 2 },
  eyebrow: { color: colors.cyan, ...display, ...typography.label, textTransform: "uppercase" },
  title: { color: colors.text, ...display, ...typography.title, marginTop: spacing.md, marginBottom: spacing.sm },
  subtitle: { color: colors.secondary, ...body, ...typography.body, marginBottom: spacing.lg },
  sectionTitle: { color: colors.text, ...display, ...typography.section, marginTop: spacing.xl, marginBottom: spacing.sm, textTransform: "uppercase" },
  label: { color: colors.muted, ...display, ...typography.label, textTransform: "uppercase", marginBottom: spacing.xs },
  input: { minHeight: 48, borderWidth: borders.thin, borderColor: colors.border, backgroundColor: colors.input, color: colors.text, ...body, ...typography.body, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radii.tag },
  inputFocused: { borderColor: colors.cyan },
  inputError: { borderColor: colors.red },
  button: { minHeight: 46, borderWidth: borders.thin, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm, alignItems: "center", justifyContent: "center", borderRadius: radii.tag, marginTop: spacing.sm },
  buttonPrimary: { borderColor: colors.orange, backgroundColor: colors.orange },
  buttonSecondary: { borderColor: colors.borderStrong, backgroundColor: colors.panel },
  buttonGhost: { borderColor: colors.border, backgroundColor: "transparent" },
  buttonDanger: { borderColor: colors.red, backgroundColor: "transparent" },
  buttonCompact: { minHeight: 34, paddingHorizontal: spacing.md, marginTop: spacing.xs },
  buttonPressed: { opacity: 0.72 },
  buttonText: { color: colors.background, ...display, ...typography.button, textTransform: "uppercase" },
  buttonTextSecondary: { color: colors.text },
  buttonTextGhost: { color: colors.cyan },
  buttonTextDanger: { color: colors.red },
  buttonDisabled: { borderColor: colors.disabled, backgroundColor: "transparent", opacity: 0.48 },
  buttonTextDisabled: { color: colors.disabled },
  error: { color: colors.red, ...body, ...typography.caption, borderLeftWidth: borders.accent, borderLeftColor: colors.red, paddingLeft: spacing.sm, marginTop: spacing.sm, lineHeight: 20 },
  status: { color: colors.secondary, ...body, ...typography.caption, marginTop: spacing.sm, lineHeight: 18 },
  card: { borderWidth: borders.thin, borderColor: colors.border, backgroundColor: colors.surface, padding: spacing.md, borderRadius: radii.card, marginBottom: spacing.sm },
  cardSelected: { borderColor: colors.cyan, backgroundColor: colors.cyanDim },
  cardHostile: { borderLeftColor: colors.red, borderLeftWidth: borders.accent },
  cardTitle: { color: colors.text, ...display, fontSize: 14, lineHeight: 20, marginBottom: spacing.xs },
  cardBody: { color: colors.secondary, ...body, ...typography.caption },
  cardMeta: { color: colors.cyan, ...display, ...typography.meta, marginTop: spacing.sm, textTransform: "uppercase" },
  panel: { borderWidth: borders.thin, borderColor: colors.border, backgroundColor: colors.panel, padding: spacing.lg, borderRadius: radii.card },
  activePanel: { borderColor: colors.cyanDim, backgroundColor: colors.player },
  emptyState: { borderLeftWidth: borders.accent, borderLeftColor: colors.borderStrong, paddingLeft: spacing.sm, marginTop: spacing.sm, marginBottom: spacing.sm },
  secondaryActions: { flexDirection: "row", gap: spacing.sm },
  divider: { height: borders.thin, backgroundColor: colors.border, marginVertical: spacing.md },
  combatTopBar: { minHeight: 52, flexDirection: "row", alignItems: "center", paddingHorizontal: spacing.sm, borderBottomWidth: borders.thin, borderColor: colors.border, backgroundColor: colors.panel },
  iconButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
  menuIcon: { color: colors.cyan, ...display, fontSize: 19 },
  combatTopTitle: { color: colors.text, ...display, fontSize: 15, lineHeight: 20, marginLeft: spacing.xs, flex: 1 },
  chatList: { flex: 1, backgroundColor: colors.background },
  chatContent: { paddingHorizontal: spacing.md, paddingTop: spacing.md, paddingBottom: spacing.md },
  message: { maxWidth: "90%", paddingHorizontal: spacing.md, paddingVertical: spacing.sm, marginBottom: spacing.sm, borderWidth: borders.thin, borderRadius: radii.bubble },
  messageGrouped: { marginBottom: spacing.xs, borderTopWidth: 0 },
  messageLeft: { alignSelf: "flex-start", backgroundColor: colors.dm, borderColor: colors.border, borderLeftColor: colors.borderStrong, borderLeftWidth: borders.accent, borderTopLeftRadius: 2 },
  messageRight: { alignSelf: "flex-end", backgroundColor: colors.player, borderColor: colors.cyanDim, borderRightColor: colors.cyan, borderRightWidth: borders.accent, borderTopRightRadius: 2 },
  messageDice: { alignSelf: "flex-start", backgroundColor: colors.dice, borderColor: colors.violet, borderLeftWidth: borders.accent, maxWidth: "82%" },
  messageCreature: { backgroundColor: colors.creature, borderLeftColor: colors.red },
  messageSender: { color: colors.muted, ...display, ...typography.meta, textTransform: "uppercase", marginBottom: spacing.xs },
  messageText: { color: colors.text, ...body, ...typography.chat },
  composerArea: { paddingHorizontal: spacing.sm, paddingTop: spacing.sm, borderTopWidth: borders.thin, borderColor: colors.border, backgroundColor: colors.panel },
  commandInput: { minHeight: 46, maxHeight: 52, borderWidth: borders.thin, borderColor: colors.borderStrong, backgroundColor: colors.input, color: colors.text, ...body, ...typography.chat, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radii.tag },
  keyboardHint: { color: colors.cyan, ...display, ...typography.meta, marginTop: spacing.xs, textAlign: "right" },
  interpretationBox: { borderLeftWidth: borders.accent, borderLeftColor: colors.cyan, backgroundColor: colors.panel, paddingLeft: spacing.sm, paddingRight: spacing.sm, paddingVertical: spacing.sm, marginBottom: spacing.sm, borderRadius: radii.tag },
  interpretationDetail: { color: colors.secondary, ...body, ...typography.caption, marginTop: spacing.xs },
  interpretationResolved: { color: colors.green, ...display, ...typography.meta, marginTop: spacing.xs },
  interpretationWarning: { color: colors.orange, ...display, ...typography.meta, marginTop: spacing.xs },
  suggestionChip: { borderWidth: borders.thin, borderColor: colors.cyanDim, backgroundColor: colors.surface, padding: spacing.sm, marginTop: spacing.xs, borderRadius: radii.tag },
  suggestionText: { color: colors.cyan, ...display, fontSize: 12 },
  suggestionDetail: { color: colors.muted, ...body, ...typography.meta, marginTop: 2 },
  skipButton: { borderWidth: borders.thin, borderColor: colors.orange, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, borderRadius: radii.tag },
  skipText: { color: colors.orange, ...display, ...typography.meta, textTransform: "uppercase" },
  semanticDefault: { color: colors.text },
  semanticCharacter: { color: colors.cyan, fontWeight: "600" },
  semanticCreature: { color: colors.red, fontWeight: "600" },
  semanticItem: { color: colors.amber, fontWeight: "600" },
  semanticSpell: { color: colors.violet, fontWeight: "600" },
  semanticAction: { color: colors.orange, fontWeight: "600" },
  semanticDamage: { color: "#e98b68", fontWeight: "700" },
  semanticDice: { color: colors.violet, fontWeight: "600" },
  overviewBackdrop: { flex: 1, backgroundColor: colors.overlay, paddingHorizontal: spacing.md },
  overviewPanel: { maxHeight: "88%", backgroundColor: colors.panelStrong, borderWidth: borders.thin, borderColor: colors.cyan, borderRadius: radii.modal },
  overviewHeader: { minHeight: 52, flexDirection: "row", alignItems: "center", paddingLeft: spacing.lg, borderBottomWidth: borders.thin, borderColor: colors.border },
  overviewTitle: { flex: 1, color: colors.text, ...display, fontSize: 15, lineHeight: 20 },
  closeButton: { width: 46, height: 46, alignItems: "center", justifyContent: "center" },
  closeText: { color: colors.cyan, ...display, fontSize: 22 },
  overviewContent: { padding: spacing.lg, paddingBottom: spacing.xxl },
  overviewMeta: { color: colors.cyan, ...display, ...typography.meta, lineHeight: 16, marginBottom: spacing.sm },
  overviewSectionTitle: { color: colors.cyan, ...display, ...typography.label, textTransform: "uppercase", marginTop: spacing.md, marginBottom: spacing.sm },
  overviewParticipant: { flexDirection: "row", alignItems: "center", borderBottomWidth: borders.thin, borderColor: colors.border, paddingVertical: spacing.sm },
  overviewName: { color: colors.text, ...body, fontSize: 14, lineHeight: 20 },
  overviewBody: { color: colors.secondary, ...body, ...typography.caption },
  inspectorPanel: { maxHeight: "82%", backgroundColor: colors.panelStrong, borderWidth: borders.thin, borderColor: colors.cyan, borderRadius: radii.modal },
  semanticInspectorKind: { color: colors.orange, ...display, ...typography.label, marginBottom: spacing.sm },
  inspectorRow: { borderBottomWidth: borders.thin, borderColor: colors.border, paddingVertical: spacing.sm },
  inspectorLabel: { color: colors.cyan, ...display, ...typography.label, textTransform: "uppercase", marginBottom: 2 },
  presentationSettings: { borderTopWidth: borders.thin, borderColor: colors.border, marginTop: spacing.lg, paddingTop: spacing.xs },
  settingRow: { minHeight: 46, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  volumeRow: { minHeight: 46, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  volumeControls: { flexDirection: "row", gap: spacing.sm },
  volumeButton: { color: colors.cyan, borderWidth: borders.thin, borderColor: colors.border, minWidth: 36, paddingVertical: spacing.xs, textAlign: "center", ...display, fontSize: 16 },
  progress: { marginBottom: spacing.xs },
  progressLabel: { color: colors.secondary, ...display, ...typography.meta, marginTop: spacing.sm },
  progressTrack: { height: 3, backgroundColor: colors.border, marginTop: spacing.sm, marginBottom: spacing.xs },
  progressFill: { height: 3, backgroundColor: colors.cyan },
  choiceRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginTop: spacing.sm },
  smallChoice: { borderWidth: borders.thin, borderColor: colors.border, paddingVertical: spacing.xs, paddingHorizontal: spacing.sm, borderRadius: radii.tag },
  smallChoiceSelected: { borderColor: colors.cyan, backgroundColor: colors.cyanDim },
  smallChoiceText: { color: colors.text, ...display, ...typography.meta },
  removeText: { color: colors.red, ...display, ...typography.meta, marginTop: spacing.sm },
  editText: { color: colors.cyan, ...display, ...typography.meta },
  serverOption: { borderWidth: borders.thin, borderColor: colors.border, backgroundColor: colors.surface, padding: spacing.md, borderRadius: radii.card, marginBottom: spacing.sm },
  serverOptionSelected: { borderColor: colors.cyan, backgroundColor: colors.cyanDim },
  connected: { color: colors.green, ...display, ...typography.meta, marginTop: spacing.sm },
  version: { color: colors.muted, ...display, ...typography.meta, textAlign: "center", marginTop: spacing.xxl },
  diagnostic: { borderLeftWidth: borders.accent, borderLeftColor: colors.red, backgroundColor: colors.panel, paddingLeft: spacing.sm, paddingRight: spacing.sm, paddingVertical: spacing.sm, marginTop: spacing.md, borderRadius: radii.tag },
  diagnosticTitle: { color: colors.red, ...display, fontSize: 14, lineHeight: 20, marginBottom: spacing.xs },
  diagnosticMeta: { color: colors.muted, ...body, ...typography.meta, lineHeight: 17, marginTop: spacing.xs },
  diagnosticActions: { flexDirection: "row", gap: spacing.sm },
  detailsToggle: { color: colors.cyan, ...display, ...typography.meta, marginTop: spacing.sm },
});
