import { StyleSheet } from "react-native";
import { colors } from "./colors.js";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { padding: 18, paddingBottom: 36 },
  safe: { flex: 1, backgroundColor: colors.background },
  eyebrow: { color: colors.cyan, fontSize: 11, letterSpacing: 2, textTransform: "uppercase" },
  title: { color: colors.text, fontSize: 30, fontWeight: "400", marginTop: 10, marginBottom: 8 },
  subtitle: { color: colors.muted, fontSize: 14, lineHeight: 21, marginBottom: 20 },
  sectionTitle: { color: colors.text, fontSize: 19, fontWeight: "400", marginTop: 24, marginBottom: 10 },
  label: { color: colors.muted, fontSize: 11, letterSpacing: 1, textTransform: "uppercase", marginBottom: 7 },
  input: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceRaised, color: colors.text, padding: 13, fontSize: 15, borderRadius: 3 },
  button: { borderWidth: 1, borderColor: colors.orange, padding: 14, alignItems: "center", borderRadius: 3, marginTop: 14 },
  buttonText: { color: colors.orange, fontSize: 12, letterSpacing: 1, textTransform: "uppercase" },
  buttonDisabled: { opacity: 0.4 },
  error: { color: colors.red, borderLeftWidth: 2, borderLeftColor: colors.red, paddingLeft: 10, marginTop: 14, lineHeight: 20 },
  status: { color: colors.muted, marginTop: 12, lineHeight: 20 },
  card: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 14, borderRadius: 3, marginBottom: 9 },
  cardSelected: { borderColor: colors.cyan, backgroundColor: "#0b171b" },
  cardHostile: { borderColor: colors.red },
  cardTitle: { color: colors.text, fontSize: 16, marginBottom: 5 },
  cardBody: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  cardMeta: { color: colors.cyan, fontSize: 11, marginTop: 8 },
  combatTopBar: { minHeight: 50, flexDirection: "row", alignItems: "center", paddingHorizontal: 10, borderBottomWidth: 1, borderColor: colors.border, backgroundColor: colors.background },
  iconButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
  menuIcon: { color: colors.cyan, fontSize: 22 },
  combatTopTitle: { color: colors.text, fontSize: 18, marginLeft: 4, flex: 1 },
  chatList: { flex: 1 },
  chatContent: { paddingHorizontal: 14, paddingTop: 12, paddingBottom: 12 },
  message: { maxWidth: "88%", padding: 10, marginBottom: 7, backgroundColor: colors.surface, borderLeftWidth: 2 },
  messageLeft: { alignSelf: "flex-start", borderLeftColor: colors.border },
  messageRight: { alignSelf: "flex-end", borderLeftColor: colors.cyan },
  messageDice: { borderLeftColor: colors.violet },
  messageSender: { color: colors.muted, fontSize: 10, textTransform: "uppercase", marginBottom: 4 },
  messageText: { color: colors.text, lineHeight: 20 },
  composerArea: { paddingHorizontal: 10, paddingTop: 7, borderTopWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  commandRow: { flexDirection: "row", alignItems: "center", gap: 7 },
  commandInput: { flex: 1, minHeight: 44, maxHeight: 50, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceRaised, color: colors.text, paddingHorizontal: 12, paddingVertical: 9, fontSize: 15, borderRadius: 3 },
  sendButton: { width: 46, height: 46, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.orange, borderRadius: 23 },
  sendIcon: { color: colors.orange, fontSize: 25, lineHeight: 28 },
  overviewBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,.68)", paddingHorizontal: 14 },
  overviewPanel: { maxHeight: "88%", backgroundColor: colors.surfaceRaised, borderWidth: 1, borderColor: colors.cyan, borderRadius: 4 },
  overviewHeader: { minHeight: 50, flexDirection: "row", alignItems: "center", paddingLeft: 14, borderBottomWidth: 1, borderColor: colors.border },
  overviewTitle: { flex: 1, color: colors.text, fontSize: 17 },
  closeButton: { width: 46, height: 46, alignItems: "center", justifyContent: "center" },
  closeText: { color: colors.cyan, fontSize: 28, fontWeight: "300" },
  overviewContent: { padding: 14, paddingBottom: 24 },
  overviewMeta: { color: colors.muted, fontSize: 11, lineHeight: 18, marginBottom: 8 },
  overviewSectionTitle: { color: colors.cyan, fontSize: 11, letterSpacing: 1, textTransform: "uppercase", marginTop: 13, marginBottom: 7 },
  overviewParticipant: { flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderColor: colors.border, paddingVertical: 9 },
  overviewName: { color: colors.text, fontSize: 15 },
  overviewBody: { color: colors.muted, fontSize: 12, lineHeight: 18 },
});
