export const goblin = Object.freeze({
  id: "goblin",
  kind: "creature",
  name: "Goblin",
  hitPoints: 7,
  armorClass: 13,
  initiativeBonus: 2,
  abilityScores: {
    strength: 8,
    dexterity: 14,
    constitution: 10,
    intelligence: 10,
    wisdom: 8,
    charisma: 8,
  },
  weapon: {
    id: "scimitar",
    name: "Scimitar",
    ability: "dexterity",
    attackBonus: 2,
    damageDie: 6,
    damageBonus: 0,
    damageType: "slashing",
  },
  controller: "ai",
  faction: "monsters",
});
