export const ActionType = Object.freeze({
  ATTACK: "ATTACK",
  DODGE: "DODGE",
  PASS: "PASS",
});

export const IntentError = Object.freeze({
  INVALID_ACTOR: "INVALID_ACTOR",
  NOT_ACTOR_TURN: "NOT_ACTOR_TURN",
  INVALID_TARGET: "INVALID_TARGET",
  TARGET_DEFEATED: "TARGET_DEFEATED",
  ACTION_NOT_AVAILABLE: "ACTION_NOT_AVAILABLE",
  COMBAT_NOT_ACTIVE: "COMBAT_NOT_ACTIVE",
});
